---
driver:
  name: molecule-proxmox
  options:
    proxmox_secrets: $HOME/.molecule-proxmox/proxmox-secrets.yml
    full: true

platforms:
  - name: molecule-debian-13
    newid: 1000
    template_name: debian-13-tmp
    ipconfig:
      ipconfig0: 'ip=10.0.10.20/22,gw=10.0.8.2'
  - name: molecule-debian-12
    newid: 1001
    template_name: debian-12-tmp
    ipconfig:
      ipconfig0: 'ip=10.0.10.21/22,gw=10.0.8.2'
  - name: molecule-ubuntu-22.04
    newid: 1002
    template_name: ubuntu-22.04-tmp
    ipconfig:
      ipconfig0: 'ip=10.0.10.22/22,gw=10.0.8.2'
  - name: molecule-ubuntu-24.04
    newid: 1003
    template_name: ubuntu-24.04-tmp
    ipconfig:
      ipconfig0: 'ip=10.0.10.23/22,gw=10.0.8.2'

provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 3
  lint:
    name: "ansible-lint"
